package com.knowledge.mnlin.page.pages;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY Page : PageMainEnterProcessor
 */
class FirstPage$Page$AppearanceType {
    static int autoGenerateAppearanceType(){
        return 0;
    }
}
