package com.knowledge.mnlin.page.pages;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY Page : PageMainEnterProcessor
 */
class FirstPage$Page$LauncherType {
    static int autoGenerateLauncherType() {
        return 0;
    }
}
