package com.knowledge.mnlin.page_processor.consts;

/**************************************
 * function : help to auto generate file
 *
 * Created on 2019/10/26  17:05
 * @author mnlin0905@gmail.com
 **************************************/

public class ProcessorConst {
    /**
     * waring message
     */
    public static final String PAGE_MODULE_WARNING_TIP = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY Page : Page***Processor\n";

    /**
     * module base package
     */
    public static final String PAGE_MODULE_PACKAGE  ="com.knowledge.mnlin";

    /**
     * page-main-lib package
     */
    public static final String PAGE_MODULE_MAIN_PACKAGE = PAGE_MODULE_PACKAGE + ".page";

    /**
     * page-annotation-lib package
     */
    public static final String PAGE_MODULE_ANNOTATION_PACKAGE = PAGE_MODULE_PACKAGE + ".page_annotation";

    /**
     * page-processor-lib package
     */
    public static final String PAGE_MODULE_PROCESSOR_PACKAGE = PAGE_MODULE_PACKAGE + ".page_processor";


    //////////////////////////////////////////////////////////
    //// PageProcessorAnnotationsPackagePath
    //////////////////////////////////////////////////////////

    private static final String PATH_ANNOTATION_PAGE_BASE = PAGE_MODULE_PACKAGE + ".page_annotation.annotations";

    public static final String PATH_ANNOTATION_PAGE_ENTER_POINT = PATH_ANNOTATION_PAGE_BASE + ".PageEnterPoint";
    public static final String PATH_ANNOTATION_PAGE_TAG = PATH_ANNOTATION_PAGE_BASE + ".PageTag";
    public static final String PATH_ANNOTATION_PAGE_TRANS_ANIM = PATH_ANNOTATION_PAGE_BASE + ".InjectPageTransAnim";

    //////////////////////////////////////////////////////////
    //// PageMainEnterProcessor
    //////////////////////////////////////////////////////////

    public static final String PAGE_ENTER_POINT_METHOD = "getPageEnterPoint";

    //////////////////////////////////////////////////////////
    //// PageTagProcessor
    //////////////////////////////////////////////////////////

    //////////////////////////////////////////////////////////
    //// PageTransAnimProcessor
    //////////////////////////////////////////////////////////

    public static final String PAGE_TRANS_ANIM_METHOD = "autoGenerateTransAnim";

    //////////////////////////////////////////////////////////
    //// auto-code annotation
    //////////////////////////////////////////////////////////

    public static final String PAGE_RETURN_NULLABLE = "android.annotation.Nullable";
    public static final String PAGE_RETURN_NonNull = "android.annotation.NonNull";
}
