package com.knowledge.mnlin.page_processor.consts;

import com.knowledge.mnlin.page_annotation.consts.PageGenPackageConst;
import com.squareup.javapoet.ClassName;

/**************************************
 * function : help to auto generate file
 *
 * Created on 2019/10/26  17:05
 * @author mnlin0905@gmail.com
 **************************************/

public class ProcessorConst {
    /**
     * waring message
     */
    public static final String PAGE_MODULE_WARNING_TIP = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY Page : Page***Processor\n";

    //////////////////////////////////////////////////////////
    //// PageProcessorAnnotationsPackagePath
    //////////////////////////////////////////////////////////

    private static final String PATH_ANNOTATION_PAGE_BASE = PageGenPackageConst.PAGE_MODULE_ANNOTATION_PACKAGE + ".annotations";

    public static final String PATH_ANNOTATION_PAGE_ENTER_POINT = PATH_ANNOTATION_PAGE_BASE + ".PageEnterPoint";
    public static final String PATH_ANNOTATION_PAGE_TAG = PATH_ANNOTATION_PAGE_BASE + ".PageTag";
    public static final String PATH_ANNOTATION_PAGE_INJECT_TRANS_ANIM = PATH_ANNOTATION_PAGE_BASE + ".InjectPageTransAnim";
    public static final String PATH_ANNOTATION_PAGE_INJECT_APPEARANCE_TYPE = PATH_ANNOTATION_PAGE_BASE + ".InjectPageAppearanceType";
    public static final String PATH_ANNOTATION_PAGE_INJECT_LAUNCHER_TYPE = PATH_ANNOTATION_PAGE_BASE + ".InjectPageLauncherType";
    public static final String PATH_ANNOTATION_PAGE_INJECT_LAYOUT_RES = PATH_ANNOTATION_PAGE_BASE + ".InjectPageLayoutRes";
    public static final String PATH_ANNOTATION_PAGE_TRANS_ANIM_TAG = PATH_ANNOTATION_PAGE_BASE + ".PageTransAnimTag";

    //////////////////////////////////////////////////////////
    //// main-class's class-name / or annotation
    //////////////////////////////////////////////////////////

    public static final ClassName COMMON_CLASS_PAGE_TRANS_ANIMATION = ClassName.get(PageGenPackageConst.PAGE_MODULE_MAIN_PACKAGE + ".interfaces", "PageTransAnimation");
    public static final ClassName COMMON_CLASS_PAGE_GEN_COMBINE_OPERATE = ClassName.get(PageGenPackageConst.PAGE_MODULE_MAIN_PACKAGE + ".interfaces", "PageGenCombineOperate");
    public static final ClassName COMMON_CLASS_PAGE = ClassName.get(PageGenPackageConst.PAGE_MODULE_MAIN_PACKAGE + ".interfaces", "Page");
    public static final ClassName COMMON_CLASS_PAGE_IMPL = ClassName.get(PageGenPackageConst.PAGE_MODULE_MAIN_PACKAGE + ".core", "PageImpl");
    public static final ClassName COMMON_ANNOTATION_NULLABLE = ClassName.get( "android.annotation","Nullable");
    public static final ClassName COMMON_ANNOTATION_NONNULL = ClassName.get( "android.annotation","NonNull");

    //////////////////////////////////////////////////////////
    //// PageTagProcessor  method
    //////////////////////////////////////////////////////////

    public static final String PAGE_TRANS_ANIM_METHOD = "autoGenerateTransAnim";

    //////////////////////////////////////////////////////////
    //// InjectAppearanceTypeProcessor  method
    //////////////////////////////////////////////////////////

    public static final String PAGE_APPEARANCE_TYPE_METHOD = "autoGenerateAppearanceType";

    //////////////////////////////////////////////////////////
    //// InjectLauncherTypeProcessor  method
    //////////////////////////////////////////////////////////

    public static final String PAGE_LAUNCHER_TYPE_METHOD = "autoGenerateLauncherType";

    //////////////////////////////////////////////////////////
    //// InjectLayoutResProcessor  method
    //////////////////////////////////////////////////////////

    public static final String PAGE_LAYOUT_RES_METHOD = "autoGenerateLayoutRes";

    //////////////////////////////////////////////////////////
    //// PageTransAnimProcessor  method : same to {@link PageGenCombineOperate}
    //////////////////////////////////////////////////////////


}
