package com.example.Consts;

/**************************************
 * function : help to auto generate file
 *
 * Created on 2019/10/26  17:05
 * @author 80270427
 **************************************/

public class ProcessorConst {
    /**
     * waring message
     */
    public static final String PAGE_MUDULE_WARNING_TIP = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY Page : PageMainEnterProcessor";

    //////////////////////////////////////////////////////////
    //// PageMainEnterProcessor
    //////////////////////////////////////////////////////////

    public static final String PAGE_MUDULE_PACKAGE = "com.knowledge.mnlin.simulatedialog";

    public static final String PAGE_ENTER_POINT_CLASS = "PageProcessor$EnterPoint";

    public static final String PAGE_ENTER_POINT_METHOD = "getPageEnterPoint";
}
